import { useEffect, useState } from 'react';
import { FileText, Plus, Download, Trash2, AlertTriangle, Shield, Calendar } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import ThreatBadge from '../components/ThreatBadge';
import type { Report } from '../lib/types';

const SAMPLE_REPORTS: Report[] = [
  {
    id: 'r1', user_id: 'demo', dataset_id: null,
    title: 'DarkWeb Marketplace Analysis Q1 2024',
    summary: 'Comprehensive analysis of underground marketplace operators identified across 14 onion domains. High-value targets include ransomware group NullByte Collective and carding network operators.',
    threat_level: 'critical', entity_count: 47,
    findings: [
      { type: 'Ransomware', description: 'Active C2 infrastructure detected on nullbyte-payments.onion', severity: 'critical' },
      { type: 'Crypto Trail', description: '3 BTC wallets linked to known money laundering operations', severity: 'high' },
      { type: 'Identity', description: 'Operator alias "The Architect" confirmed cross-platform activity', severity: 'medium' },
    ],
    created_at: '2024-03-15T10:30:00Z',
  },
  {
    id: 'r2', user_id: 'demo', dataset_id: null,
    title: 'Carding Forum Hierarchy Report',
    summary: 'Structural analysis of carding forum members identifying 3 moderators and 12 active vendors. Email correlation with previous datasets achieved 78% match rate.',
    threat_level: 'high', entity_count: 32,
    findings: [
      { type: 'Identity Link', description: 'l33t_c4rd3r linked to shadows_deep@tutanota.com via PGP key', severity: 'high' },
      { type: 'Infrastructure', description: 'Bulletproof hosting on 185.220.101.47 serves 4 distinct marketplaces', severity: 'high' },
    ],
    created_at: '2024-03-14T08:15:00Z',
  },
  {
    id: 'r3', user_id: 'demo', dataset_id: null,
    title: 'Credential Market Operator Profile',
    summary: 'Profile of credential marketplace vendor CredKing including payment addresses and operational security patterns.',
    threat_level: 'medium', entity_count: 18,
    findings: [
      { type: 'Financial', description: 'ETH wallet 0xAb58...eC9B shows 47 transactions in past 30 days', severity: 'medium' },
    ],
    created_at: '2024-03-12T14:45:00Z',
  },
];

const LEVEL_STYLES = {
  critical: 'text-red-400 bg-red-500/10 border-red-500/25',
  high: 'text-orange-400 bg-orange-500/10 border-orange-500/25',
  medium: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/25',
  low: 'text-green-400 bg-green-500/10 border-green-500/25',
};

function exportReportPDF(report: Report) {
  const lines = [
    `AI TOR ENTITY ANALYZER — INTELLIGENCE REPORT`,
    `${'='.repeat(60)}`,
    ``,
    `Title: ${report.title}`,
    `Date: ${new Date(report.created_at).toLocaleString()}`,
    `Threat Level: ${report.threat_level.toUpperCase()}`,
    `Entities Analyzed: ${report.entity_count}`,
    ``,
    `EXECUTIVE SUMMARY`,
    `-`.repeat(40),
    report.summary,
    ``,
    `KEY FINDINGS`,
    `-`.repeat(40),
    ...report.findings.map((f, i) => `${i + 1}. [${f.severity.toUpperCase()}] ${f.type}: ${f.description}`),
    ``,
    `— END OF REPORT —`,
    `Generated by AI TOR Entity Analyzer`,
  ];
  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${report.title.replace(/\s+/g, '_')}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function Reports() {
  const { user } = useAuth();
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selected, setSelected] = useState<Report | null>(null);

  useEffect(() => {
    if (!user) return;
    supabase.from('reports').select('*').eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .then(({ data }) => { setReports(data ?? []); setLoading(false); });
  }, [user]);

  const display = reports.length > 0 ? reports : SAMPLE_REPORTS;

  async function generateReport() {
    if (!user) return;
    setGenerating(true);
    const { data: ents } = await supabase.from('entities').select('*').eq('user_id', user.id).limit(50);
    const entities = ents ?? [];

    const critical = entities.filter((e: { threat_score: number }) => e.threat_score >= 80);
    const level = critical.length >= 5 ? 'critical' : critical.length >= 2 ? 'high' : entities.length > 0 ? 'medium' : 'low';

    const report = {
      user_id: user.id,
      title: `Intelligence Report — ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`,
      summary: `Automated analysis completed. ${entities.length} entities extracted. ${critical.length} critical threats identified.`,
      threat_level: level,
      entity_count: entities.length,
      findings: critical.slice(0, 5).map((e: { type: string; value: string; threat_score: number }) => ({
        type: e.type.charAt(0).toUpperCase() + e.type.slice(1),
        description: `High-threat ${e.type} identified: ${e.value} (score: ${e.threat_score})`,
        severity: 'critical' as const,
      })),
    };

    const { data: saved } = await supabase.from('reports').insert(report).select().maybeSingle();
    if (saved) {
      setReports(prev => [saved as Report, ...prev]);
      await supabase.from('activity_logs').insert({
        user_id: user.id, action: 'Report generated', details: report.title,
      });
    }
    setGenerating(false);
  }

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-white font-mono">INTELLIGENCE REPORTS</h2>
          <p className="text-xs text-gray-500 font-mono mt-0.5">{display.length} REPORTS AVAILABLE</p>
        </div>
        <button
          onClick={generateReport}
          disabled={generating}
          className="flex items-center gap-2 bg-cyan-500/10 hover:bg-cyan-500/20 border border-cyan-500/30 text-cyan-400 px-4 py-2 rounded-lg text-sm font-mono font-bold transition-all disabled:opacity-50"
        >
          <Plus size={14} className={generating ? 'animate-spin' : ''} />
          {generating ? 'GENERATING...' : 'GENERATE REPORT'}
        </button>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-5">
        {/* Report list */}
        <div className="xl:col-span-1 space-y-3">
          {(loading ? [] : display).map(r => (
            <button
              key={r.id}
              onClick={() => setSelected(r)}
              className={`w-full text-left bg-gray-900 border rounded-xl p-4 transition-all hover:border-cyan-500/30 ${selected?.id === r.id ? 'border-cyan-500/40 bg-cyan-500/5' : 'border-gray-800/60'}`}
            >
              <div className="flex items-start justify-between gap-2 mb-2">
                <FileText size={14} className="text-cyan-400 flex-shrink-0 mt-0.5" />
                <span className={`text-[10px] font-mono font-bold border rounded px-1.5 py-0.5 ${LEVEL_STYLES[r.threat_level]}`}>
                  {r.threat_level.toUpperCase()}
                </span>
              </div>
              <p className="text-xs font-mono text-gray-200 line-clamp-2 mb-2">{r.title}</p>
              <div className="flex items-center gap-3 text-[10px] font-mono text-gray-500">
                <span className="flex items-center gap-1"><Shield size={9} />{r.entity_count} entities</span>
                <span className="flex items-center gap-1"><Calendar size={9} />{new Date(r.created_at).toLocaleDateString()}</span>
              </div>
            </button>
          ))}
          {loading && <div className="text-center py-8 text-gray-600 font-mono text-sm">LOADING...</div>}
        </div>

        {/* Report detail */}
        <div className="xl:col-span-2">
          {selected ? (
            <div className="bg-gray-900 border border-gray-800/60 rounded-xl p-6 space-y-5">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h3 className="text-base font-bold text-white font-mono">{selected.title}</h3>
                  <p className="text-xs text-gray-500 font-mono mt-1">{new Date(selected.created_at).toLocaleString()}</p>
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={() => exportReportPDF(selected)}
                    className="flex items-center gap-1.5 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-gray-300 px-3 py-1.5 rounded-lg text-xs font-mono transition-all"
                  >
                    <Download size={11} /> EXPORT
                  </button>
                  <button
                    onClick={async () => {
                      if (!user || selected.user_id === 'demo') return;
                      await supabase.from('reports').delete().eq('id', selected.id);
                      setReports(prev => prev.filter(r => r.id !== selected.id));
                      setSelected(null);
                    }}
                    className="flex items-center gap-1.5 bg-red-500/10 hover:bg-red-500/20 border border-red-500/25 text-red-400 px-3 py-1.5 rounded-lg text-xs font-mono transition-all"
                  >
                    <Trash2 size={11} /> DELETE
                  </button>
                </div>
              </div>

              <div className="flex items-center gap-4">
                <span className={`text-xs font-mono font-bold border rounded px-2 py-1 ${LEVEL_STYLES[selected.threat_level]}`}>
                  {selected.threat_level.toUpperCase()} THREAT
                </span>
                <span className="text-xs text-gray-400 font-mono">{selected.entity_count} entities analyzed</span>
              </div>

              <div>
                <h4 className="text-xs text-gray-500 font-mono tracking-wider mb-2">EXECUTIVE SUMMARY</h4>
                <p className="text-sm text-gray-300 leading-relaxed font-mono">{selected.summary}</p>
              </div>

              {selected.findings.length > 0 && (
                <div>
                  <h4 className="text-xs text-gray-500 font-mono tracking-wider mb-3">KEY FINDINGS</h4>
                  <div className="space-y-2">
                    {selected.findings.map((f, i) => (
                      <div key={i} className="flex items-start gap-3 bg-gray-800/40 rounded-lg px-3 py-2.5">
                        <AlertTriangle size={13} className={f.severity === 'critical' ? 'text-red-400' : f.severity === 'high' ? 'text-orange-400' : 'text-yellow-400'} />
                        <div>
                          <p className="text-xs font-mono text-gray-200"><span className="text-gray-500">[{f.type}]</span> {f.description}</p>
                        </div>
                        <ThreatBadge score={f.severity === 'critical' ? 90 : f.severity === 'high' ? 70 : 45} />
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="bg-gray-900 border border-gray-800/60 rounded-xl h-64 flex items-center justify-center">
              <div className="text-center">
                <FileText size={32} className="mx-auto text-gray-700 mb-3" />
                <p className="text-gray-500 font-mono text-sm">SELECT A REPORT TO VIEW</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
